openapi: 3.0.3
info:
  title: Swagger Pierre_le_developpeur - OpenAPI 3.0
  description: |-
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://pierre_le_developpeur.com/api/v0
tags:
  - name: likes
    description: add likes
    externalDocs:
      description: nothing
      url: http://swagger.io
  - name: log_in
    description: Back office log in
  - name: projects
    description: all about projects
  - name: data
    description: all needed data
paths:
  /data:
    get:
      tags:
        - data
      summary: Get all the data
      description: Get all the data
      operationId: getAllData
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Data'

        '404':
          description: Data not found
    put:
      tags:
        - data
      summary: Modifi contact
      description: modifi Skills, Tools, Slider, Recommendation
      operationId: modifi contact
      requestBody:
        description: modifie Contact
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Skills'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skills'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
components:
  schemas:
    Data:
      type: array
      items:
          oneOf:
            - $ref: '#/components/schemas/Projects'
            - $ref: '#/components/schemas/Skills'
            - $ref: '#/components/schemas/Tools'
            - $ref: '#/components/schemas/Slider'
            - $ref: '#/components/schemas/Contact'
            - $ref: '#/components/schemas/Recommendation'
    Projects:
      type: array
      items:
        $ref: '#/components/schemas/Project'
    Project:
      type: object
      properties:
          title:
            type: object
            properties:
              french:
                type: string
              english:
                type: string
          category:
            type: string
          date:
            type: string
          tools:
            type: array
            items: 
              properties:
                title:
                  type: string
          description:
            type: object
            properties:
              french:
                type: string
              english:
                type: string
          links:
            type: array
            items:
              properties:
                title:
                  type: string
                url:
                  type: string
                picture:
                  type: string
                  format: binary
                alt:
                  type: string
          slider:
            type: array
            items:
              properties:
                picture:
                  type: string
                alt:
                  type: string
                content:
                  type: object
                  properties:
                    french:
                      type: string
                    english:
                      type: string
          resum:
            type: object
            properties:
              french:
                type: string
              english:
                type: string
          skills:
            type: array
            items:
              properties:
                title:
                  type: string
          likes:
            type: integer
            format: int64
    Skills:  
      type: array
      items:
        properties:
          picture:
            type: string
          alt:
            type: string
          title:
            type: string
          diplayTitle:
            type: object
            properties:
              french:
                type: string
              english:
                type: string
          likes:
            type: integer
            format: int64
    Tools:
      type: array
      items:
        properties:
          picture:
            type: string
          alt:
            type: string
          title:
            type: string
          likes:
            type: integer
            format: int64
    Slider:
      type: array
      items:
        properties:
          alt:
            type: string
          picture:
            type: string
          content:
            type: object
            properties:
              french:
                type: string
              english:
                type: string
    Contact:
      type: object
      properties:
        content:
          type: object
          properties:
            french:
              type: string
            english:
              type: string
        cv:
          type: object
          properties:
            french:
              type: string
            english:
              type: string
        likes:
            type: integer
            format: int64
    Recommendation:
      type: object
      properties:
        french:
          type: string
        english:
          type: string
        likes:
            type: integer
            format: int64
    Dashboard:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header